version: '3.9'

services:
  db: 
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      - ./dumps/public_dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  
  backend: 
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      PGHOST: "db"
      PGUSER: $POSTGRES_USER
      PGPASSWORD: $POSTGRES_PASSWORD
      PGDATABASE: $POSTGRES_DB
